# Copyright (c) 2023 sparkierkan7
# Modifications Copyright (c) 2026 NicDev-Studios
# SPDX-License-Identifier: MIT

version: 2

updates:
  - package-ecosystem: gradle
    directory: "/"
    target-branch: "legacy"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    groups:
      gradle-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "legacy"
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: gradle
    directory: "/"
    target-branch: "1.20.x"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    groups:
      gradle-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "1.20.x"
    schedule:
      interval: weekly
      day: monday
      time: "07:30"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
